backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
locale: 'nl'
collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/agenda.md"
        label: "Agenda"
        name: "agenda"
        widget: "list"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Agenda", name: agenda, widget: list, fields: [
              {label: "Omschrijving", name: "omschrijving", widget: "text"},
              {label: "Datum", name: "datum", widget: "text", required: false},
              {label: "Afgelast", name: "afgelast", widget: "boolean", required: false}]}
      - file: "site/content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}     
          - {label: "Slides", name: slides, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}]}
          - {label: Youtube, name: youtube, widget: string}
      - file: "site/content/foto-impressie/_index.md"
        label: "Foto Impressie"
        name: "foto-impressie"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Slides", name: slides, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}]}
      - file: "site/content/duurzame-pedagogiek.md"
        label: "Duurzame Pedagogiek"
        name: "duurzame-pedagogiek"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/kennismaken.md"
        label: "Kennismaken"
        name: "kennismaken"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/ontstaansgeschiedenis.md"
        label: "Ontstaansgeschiedenis"
        name: "ontstaansgeschiedenis"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/openingstijden.md"
        label: "Openingstijden"
        name: "openingstijden"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Maandag", name: "maandag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" }]}
          - {label: "Dinsdag", name: "dinsdag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" }]}
          - {label: "Woensdag", name: "woensdag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" }]}
          - {label: "Donderdag", name: "donderdag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" }]}
          - {label: "Vrijdag", name: "vrijdag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" }]}
          - {label: "Zaterdag", name: "zaterdag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" },
              { label: "Niet weergeven", value: "hide" }]}
          - {label: "Zondag", name: "zondag", widget: "select",  options: [
              { label: "Ochtend", value: "ochtend" },
              { label: "Dagopvang", value: "dagopvang" },
              { label: "Hele dagopvang", value: "heledag" },
              { label: "Niet weergeven", value: "hide" }]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/peuterpedagogie.md"
        label: "Peuterpedagogie"
        name: "peuterpedagogie"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/peuterspeelgroep.md"
        label: "Peuterspeelgroep"
        name: "peuterspeelgroep"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/reviews-van-ouders.md"
        label: "Reviews van Ouders"
        name: "reviews-van-ouders"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/tarieven.md"
        label: "Tarieven"
        name: "tarieven"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Tarieven", name: tarieven, widget: list, fields: [
              {label: "Opvangtijden", name: "opvangtijden", widget: "text"},
              {label: "Bruto maandbedragen", name: "maandbedragen", widget: "text"},
              {label: "Inclusief", name: "inclusief", widget: "text"}]}
      - file: "site/content/vacatures.md"
        label: "Vacatures"
        name: "vacatures"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/veiligheid-en-kwaliteit.md"
        label: "Veiligheid en Kwaliteit"
        name: "veiligheid-en-kwaliteit"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/vve-subsidie.md"
        label: "VVE subsidie"
        name: "vve-subsidie"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}